# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servico.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'servico.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservico.proto\x12\x0b\x63\x61lculadora\"!\n\tOperandos\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\tResultado\x12\r\n\x05valor\x18\x01 \x01(\x05\x32\x46\n\x0b\x43\x61lculadora\x12\x37\n\x05Somar\x12\x16.calculadora.Operandos\x1a\x16.calculadora.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servico_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERANDOS']._serialized_start=30
  _globals['_OPERANDOS']._serialized_end=63
  _globals['_RESULTADO']._serialized_start=65
  _globals['_RESULTADO']._serialized_end=91
  _globals['_CALCULADORA']._serialized_start=93
  _globals['_CALCULADORA']._serialized_end=163
# @@protoc_insertion_point(module_scope)
